disabled_rules:
  - todo
opt_in_rules:
  - empty_count
  - explicit_init
  - force_unwrapping
  - missing_docs
  - array_init
  - closure_end_indentation
  - closure_spacing
  - contains_over_filter_count
  - empty_string
  - fallthrough
  - fatal_error_message
  - first_where
  - last_where
  - legacy_multiple
  - literal_expression_end_indentation

# Excluded paths (customize based on your project)
excluded:
  - Project.swift
  - "**/.build"
  - DerivedData

line_length:
  warning: 120
  error: 160
  ignores_comments: true
  ignores_urls: true

nesting:
  type_level: 3

file_length:
  warning: 500
  error: 1000

type_body_length:
  warning: 300
  error: 500

function_body_length:
  warning: 50
  error: 100

large_tuple:
  warning: 3
  error: 4

cyclomatic_complexity:
  warning: 10
  error: 15

reporter: "xcode"
